// tb_bridge.c
// krkrz (KiriKiri Z) plugin bridge for the D&B trainer.
// Loaded by the engine via V2Link (undecorated, __stdcall). Hosts a named
// pipe server; executes TJS code in the game process on the main thread.
// Build: zig cc -target i386-windows-gnu -shared -Wl,--kill-at -O2 -o tb_bridge.dll tb_bridge.c
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

// ---------------------------------------------------------------------------
// TJS2 structures (x86, pack 4)
// ---------------------------------------------------------------------------
#pragma pack(push, 4)

typedef struct _VSString {
    long  RefCount;      // +0
    wchar_t *LongString; // +4
    wchar_t ShortString[22]; // +8
    long  Length;        // +16
    unsigned long HeapFlag; // +20
    unsigned long Hint;   // +24
} VSString;

typedef struct _Variant {
    union {
        struct { void *Object; void *ObjThis; } closure;
        __int64 integer;
        double real;
        VSString *string;
        void *octet;
    } u;                 // +0
    unsigned long vt;    // +8
} Variant;
#define TVT_VOID 0
#define TVT_OBJECT 1
#define TVT_STRING 2
#define TVT_OCTET 3
#define TVT_INTEGER 4
#define TVT_REAL 5

// tTJSString = single pointer
typedef struct _TJSString { VSString *Ptr; } TJSString;
#pragma pack(pop)

// tTVPExceptionDesc
typedef struct _TVPExceptionDesc {
    TJSString type;
    TJSString message;
} TVPExceptionDesc;

// iTVPFunctionExporter (opaque C++ object: hidden vptr at offset 0)
typedef struct iTVPFunctionExporter iTVPFunctionExporter;
typedef int (__cdecl *QueryNarrowFn)(iTVPFunctionExporter *, const char **, void **, unsigned int);

// engine functions (resolved at V2Link)
// NOTE: krkrz exports these through __stdcall stubs generated by makestub.pl
// (see FuncStubs.cpp: "static void __stdcall TVP_Stub_..."), so we must call
// them as __stdcall even though the C++ declarations are cdecl.
typedef void *(__stdcall *GetScriptDispatchFn)(void);
typedef void (__stdcall *ExecuteExpressionFn)(const TJSString *, Variant *);
typedef void (__stdcall *ExecuteScriptFn)(const TJSString *, const TJSString *, int, Variant *);
typedef void (__stdcall *ExecuteStorageFn)(const TJSString *, void *, Variant *, int, const wchar_t *);
typedef VSString *(__stdcall *AllocVariantStringFn)(const wchar_t *);
typedef void (__stdcall *DoTryBlockFn)(void *, void *, void *, void *);

static GetScriptDispatchFn   g_getScriptDispatch = NULL;
static ExecuteExpressionFn   g_executeExpression = NULL;
static ExecuteScriptFn       g_executeScript = NULL;
static ExecuteStorageFn      g_executeStorage = NULL;
static AllocVariantStringFn  g_allocVariantString = NULL;
static DoTryBlockFn          g_doTryBlock = NULL;

static wchar_t g_logDir[1024]; // game directory (wide)
static HWND g_bridgeHwnd = NULL;

// ---------------------------------------------------------------------------
// logging
// ---------------------------------------------------------------------------
static void logStr(const char *s)
{
    wchar_t path[1100];
    if (!g_logDir[0]) return;
    wsprintfW(path, L"%ls\\tbc_bridge.log", g_logDir);
    HANDLE h = CreateFileW(path, FILE_APPEND_DATA, FILE_SHARE_READ | FILE_SHARE_WRITE,
                           NULL, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
    if (h == INVALID_HANDLE_VALUE) return;
    DWORD written = 0;
    WriteFile(h, s, (DWORD)strlen(s), &written, NULL);
    CloseHandle(h);
}

static void logStrW(const wchar_t *s)
{
    int n = (int)wcslen(s);
    char *buf = (char *)malloc(n * 4 + 1);
    if (!buf) return;
    int j = 0;
    for (int i = 0; i < n; i++) {
        wchar_t c = s[i];
        if (c < 0x80) {
            buf[j++] = (char)c;
        } else if (c < 0x800) {
            buf[j++] = (char)(0xC0 | (c >> 6));
            buf[j++] = (char)(0x80 | (c & 0x3F));
        } else {
            buf[j++] = (char)(0xE0 | (c >> 12));
            buf[j++] = (char)(0x80 | ((c >> 6) & 0x3F));
            buf[j++] = (char)(0x80 | (c & 0x3F));
        }
    }
    buf[j] = 0;
    logStr(buf);
    free(buf);
}

// ---------------------------------------------------------------------------
// UTF conversions (BMP only)
// ---------------------------------------------------------------------------
static wchar_t *utf8ToUtf16(const char *s, int len)
{
    wchar_t *out = (wchar_t *)malloc((len + 1) * 2);
    if (!out) return NULL;
    int j = 0, i = 0;
    while (i < len) {
        unsigned char c = (unsigned char)s[i];
        unsigned int cp;
        int n;
        if (c < 0x80) { cp = c; n = 1; }
        else if ((c & 0xE0) == 0xC0) { cp = c & 0x1F; n = 2; }
        else if ((c & 0xF0) == 0xE0) { cp = c & 0x0F; n = 3; }
        else { cp = c; n = 1; }
        for (int k = 1; k < n; k++) {
            if (i + k >= len) { cp = 0xFFFD; break; }
            cp = (cp << 6) | ((unsigned char)s[i + k] & 0x3F);
        }
        if (cp > 0xFFFF) cp = 0xFFFD;
        out[j++] = (wchar_t)cp;
        i += n;
    }
    out[j] = 0;
    return out;
}

static char *utf16ToUtf8(const wchar_t *s, int len)
{
    char *out = (char *)malloc(len * 3 + 1);
    if (!out) return NULL;
    int j = 0;
    for (int i = 0; i < len; i++) {
        unsigned int c = (unsigned int)s[i];
        if (c < 0x80) out[j++] = (char)c;
        else if (c < 0x800) {
            out[j++] = (char)(0xC0 | (c >> 6));
            out[j++] = (char)(0x80 | (c & 0x3F));
        } else {
            out[j++] = (char)(0xE0 | (c >> 12));
            out[j++] = (char)(0x80 | ((c >> 6) & 0x3F));
            out[j++] = (char)(0x80 | (c & 0x3F));
        }
    }
    out[j] = 0;
    return out;
}

// ---------------------------------------------------------------------------
// TVPDoTryBlock callbacks (cdecl)
// ---------------------------------------------------------------------------
typedef struct _TryData {
    TJSString ttstr;
    TJSString name;
    Variant result;
    char *error; // malloc'd utf8
} TryData;

static void __cdecl tryBlock(void *data)
{
    TryData *d = (TryData *)data;
    if (g_executeExpression) g_executeExpression(&d->ttstr, &d->result);
}

// script-mode try block (multi-statement scripts via TVPExecuteScript,
// which takes the script text directly - no storage file needed)
static void __cdecl tryBlockScript(void *data)
{
    TryData *d = (TryData *)data;
    if (g_executeScript) g_executeScript(&d->ttstr, &d->name, 0, &d->result);
}

static int __cdecl catchBlock(void *data, const TVPExceptionDesc *desc)
{
    TryData *d = (TryData *)data;
    if (desc->message.Ptr) {
        VSString *vs = desc->message.Ptr;
        const wchar_t *dataPtr = vs->LongString ? vs->LongString : vs->ShortString;
        int n = vs->Length;
        if (n < 0) n = 0;
        d->error = utf16ToUtf8(dataPtr, n);
    } else {
        d->error = _strdup("unknown TJS exception");
    }
    return 0; // swallow
}

// ---------------------------------------------------------------------------
// eval core (main thread)
// ---------------------------------------------------------------------------
// wrapper template: user code is inserted at @@USER@@.
// If <gamedir>\tbc_wrapper.txt exists it overrides the built-in template
// (lets us iterate on the wrapper without rebuilding/restarting).
// The script stores its result into global.__tbc_result__; the plugin reads
// it back via PropGet, which avoids depending on TJS's block-result feature.
static const char *DEFAULT_WRAPPER =
    "var __tbc_r;try{__tbc_r=(function(){@@USER@@"
    "})();}catch(__tbc_e){__tbc_r='!!EXCEPTION!! '+__tbc_e;}"
    "if(__tbc_r==null){__tbc_r='undefined';}"
    "global.__tbc_result__=__tbc_r.toString();";

static char *loadWrapperTemplate(void)
{
    if (!g_logDir[0]) return _strdup(DEFAULT_WRAPPER);
    wchar_t path[1100];
    wsprintfW(path, L"%ls\\tbc_wrapper.txt", g_logDir);
    FILE *f = _wfopen(path, L"rb");
    if (!f) return _strdup(DEFAULT_WRAPPER);
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = (char *)malloc((size_t)sz + 1);
    if (!buf) { fclose(f); return _strdup(DEFAULT_WRAPPER); }
    size_t got = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    buf[got] = 0;
    return buf;
}

static char *buildWrapper(const char *code, int codeLen)
{
    char *tmpl = loadWrapperTemplate();
    if (!tmpl) return NULL;
    char *marker = strstr(tmpl, "@@USER@@");
    if (!marker) {
        // no marker: treat whole template as prefix and append code
        int tl = (int)strlen(tmpl);
        char *out = (char *)malloc(tl + codeLen + 1);
        if (out) {
            memcpy(out, tmpl, tl);
            memcpy(out + tl, code, codeLen);
            out[tl + codeLen] = 0;
        }
        free(tmpl);
        return out;
    }
    int preLen = (int)(marker - tmpl);
    int postLen = (int)strlen(marker + 8);
    char *out = (char *)malloc(preLen + codeLen + postLen + 1);
    if (out) {
        memcpy(out, tmpl, preLen);
        memcpy(out + preLen, code, codeLen);
        memcpy(out + preLen + codeLen, marker + 8, postLen);
        out[preLen + codeLen + postLen] = 0;
    }
    free(tmpl);
    return out;
}

typedef struct _EvalOutcome {
    int ok;
    char *result; // malloc'd utf8 (OK case)
    char *error;  // malloc'd utf8 (ERR case)
} EvalOutcome;

// iTJSDispatch2::PropGet (vtable[4], cdecl, this first)
typedef int (__cdecl *DispatchPropGetFn)(void *self, unsigned long flag,
    const wchar_t *membername, unsigned long *hint, Variant *result, void *objthis);

// iTJSDispatch2::EnumMembers (vtable[14], cdecl, this first)
typedef int (__cdecl *DispatchEnumMembersFn)(void *self, unsigned long flag,
    void *callback, void *objthis);

static char *readGlobalResult(void)
{
    void *g = g_getScriptDispatch();
    if (!g) return _strdup("(no global)");
    void **vtbl = *(void ***)g;
    DispatchPropGetFn propGet = (DispatchPropGetFn)vtbl[4];
    Variant rv;
    memset(&rv, 0, sizeof(rv));
    unsigned long hint = 0;
    int rc = propGet(g, 0, L"__tbc_result__", &hint, &rv, NULL);
    if (rc != 0) return _strdup("(propget failed)");
    if (rv.vt != TVT_STRING || !rv.u.string) return _strdup("(non-string)");
    VSString *vs = rv.u.string;
    const wchar_t *dp = vs->LongString ? vs->LongString : vs->ShortString;
    int n = vs->Length;
    if (n < 0) n = 0;
    return utf16ToUtf8(dp, n);
}

static void doEval(const char *codeUtf8, int codeLen, EvalOutcome *outcome)
{
    outcome->ok = 0;
    outcome->result = NULL;
    outcome->error = NULL;
    if (!g_getScriptDispatch || !g_executeExpression || !g_allocVariantString || !g_doTryBlock) {
        outcome->error = _strdup("engine functions not resolved");
        return;
    }
    if (g_getScriptDispatch() == NULL) {
        outcome->error = _strdup("TJS engine not ready");
        return;
    }
    // expression mode: user code must be a single expression
    wchar_t *w16 = utf8ToUtf16(codeUtf8, codeLen);
    if (!w16) { outcome->error = _strdup("no memory"); return; }
    VSString *vs = g_allocVariantString(w16);
    free(w16);
    if (!vs) { outcome->error = _strdup("TJSAllocVariantString failed"); return; }

    TryData data;
    memset(&data, 0, sizeof(data));
    data.ttstr.Ptr = vs;
    g_doTryBlock((void *)&tryBlock, (void *)&catchBlock, NULL, &data);

    if (data.error) {
        outcome->error = data.error;
        return;
    }
    Variant *r = &data.result;
    if (r->vt == TVT_STRING && r->u.string) {
        VSString *rvs = r->u.string;
        const wchar_t *dp = rvs->LongString ? rvs->LongString : rvs->ShortString;
        int n = rvs->Length;
        if (n < 0) n = 0;
        outcome->result = utf16ToUtf8(dp, n);
        outcome->ok = 1;
    } else if (r->vt == TVT_INTEGER) {
        char buf[32];
        snprintf(buf, sizeof(buf), "%lld", (long long)r->u.integer);
        outcome->result = _strdup(buf);
        outcome->ok = 1;
    } else if (r->vt == TVT_REAL) {
        char buf[64];
        snprintf(buf, sizeof(buf), "%g", r->u.real);
        outcome->result = _strdup(buf);
        outcome->ok = 1;
    } else if (r->vt == TVT_VOID) {
        outcome->result = _strdup("undefined");
        outcome->ok = 1;
    } else {
        outcome->result = _strdup("[non-string result]");
        outcome->ok = 1;
    }
}

// script-mode eval: executes via TVPExecuteScript(name, script, mode, result),
// so full TJS syntax (for/if/try-catch/arrays) works without storage files.
static void doEvalScript(const char *codeUtf8, int codeLen, EvalOutcome *outcome)
{
    outcome->ok = 0;
    outcome->result = NULL;
    outcome->error = NULL;
    if (!g_executeScript || !g_allocVariantString || !g_doTryBlock) {
        outcome->error = _strdup("engine functions not resolved");
        return;
    }
    if (g_getScriptDispatch() == NULL) {
        outcome->error = _strdup("TJS engine not ready");
        return;
    }
    // execute via TVPExecuteScript(name, script, TJS_SCRIPT_NORMAL=0, result):
    // the script text is passed directly; no storage file or path involved.
    wchar_t *w16 = utf8ToUtf16(codeUtf8, codeLen);
    if (!w16) { outcome->error = _strdup("no memory"); return; }
    VSString *vsCode = g_allocVariantString(w16);
    free(w16);
    if (!vsCode) { outcome->error = _strdup("TJSAllocVariantString failed"); return; }
    VSString *vsName = g_allocVariantString(L"tbc_script");
    if (!vsName) { outcome->error = _strdup("TJSAllocVariantString failed"); return; }

    TryData data;
    memset(&data, 0, sizeof(data));
    data.ttstr.Ptr = vsCode;   // script text
    data.name.Ptr = vsName;    // script name (for error messages)
    g_doTryBlock((void *)&tryBlockScript, (void *)&catchBlock, NULL, &data);

    if (data.error) {
        outcome->error = data.error;
        return;
    }
    Variant *r = &data.result;
    if (r->vt == TVT_STRING && r->u.string) {
        VSString *rvs = r->u.string;
        const wchar_t *dp = rvs->LongString ? rvs->LongString : rvs->ShortString;
        int n = rvs->Length;
        if (n < 0) n = 0;
        outcome->result = utf16ToUtf8(dp, n);
        outcome->ok = 1;
    } else if (r->vt == TVT_INTEGER) {
        char buf[32];
        snprintf(buf, sizeof(buf), "%lld", (long long)r->u.integer);
        outcome->result = _strdup(buf);
        outcome->ok = 1;
    } else if (r->vt == TVT_REAL) {
        char buf[64];
        snprintf(buf, sizeof(buf), "%g", r->u.real);
        outcome->result = _strdup(buf);
        outcome->ok = 1;
    } else if (r->vt == TVT_VOID) {
        outcome->result = _strdup("undefined");
        outcome->ok = 1;
    } else {
        outcome->result = _strdup("[non-string result]");
        outcome->ok = 1;
    }
}

// ---------------------------------------------------------------------------
// LIST: enumerate registry `o` members (keys = Japanese identifiers) and
// attach each member's `name` (runtime/localized) + `id` when present.
// Implements a minimal iTJSDispatch2 (only FuncCall) used as EnumMembers
// callback; collects keys in pass 1, then PropGets name/id per key.
// ---------------------------------------------------------------------------
#define TJS_ENUM_NO_VALUE 0x00100000

typedef struct _KeyList {
    wchar_t **keys;   // heap strings
    int count;
    int cap;
} KeyList;

typedef struct _MiniDispatch {
    void **vtbl;
} MiniDispatch;

static void appendKey(KeyList *kl, const wchar_t *s, int n)
{
    if (kl->count >= kl->cap) {
        int nc = kl->cap ? kl->cap * 2 : 512;
        wchar_t **nk = (wchar_t **)realloc(kl->keys, (size_t)nc * sizeof(wchar_t *));
        if (!nk) return;
        kl->keys = nk;
        kl->cap = nc;
    }
    wchar_t *cp = (wchar_t *)malloc(((size_t)n + 1) * 2);
    if (!cp) return;
    memcpy(cp, s, (size_t)n * 2);
    cp[n] = 0;
    kl->keys[kl->count++] = cp;
}

static KeyList *g_keySink = NULL;

static long __cdecl miniFuncCall(void *self, unsigned long flag, const wchar_t *membername,
    unsigned long *hint, Variant *result, int numparams, Variant **param, void *objthis)
{
    (void)self; (void)flag; (void)membername; (void)hint; (void)objthis;
    if (g_keySink && numparams >= 1 && param[0] && param[0]->vt == TVT_STRING && param[0]->u.string) {
        VSString *vs = param[0]->u.string;
        const wchar_t *dp = vs->LongString ? vs->LongString : vs->ShortString;
        int n = vs->Length;
        if (n < 0) n = 0;
        appendKey(g_keySink, dp, n);
    }
    if (result) { result->vt = TVT_INTEGER; result->u.integer = 1; }
    return 0;
}

static long __cdecl miniQueryInterface(void *self, void *iid, void **out)
{ (void)self; (void)iid; if (out) *out = NULL; return 0x80004002; }

static unsigned long __cdecl miniAddRef(void *self) { (void)self; return 2; }

static unsigned long __cdecl miniRelease(void *self) { (void)self; return 1; }

static long __cdecl miniStub(void *self, ...) { (void)self; return 0x80004001; }

static void *miniVtbl[20];
static MiniDispatch miniDispatch;

static void initMiniDispatch(void)
{
    static int done = 0;
    if (done) return;
    done = 1;
    for (int i = 0; i < 20; i++) miniVtbl[i] = (void *)miniStub;
    // 2016-era iTJSDispatch2: [0]=AddRef [1]=Release [2]=FuncCall
    miniVtbl[0] = (void *)miniAddRef;
    miniVtbl[1] = (void *)miniRelease;
    miniVtbl[2] = (void *)miniFuncCall;
    miniDispatch.vtbl = miniVtbl;
}

static void appendUtf8(char **buf, int *len, int *cap, const char *s, int n)
{
    if (*len + n + 1 > *cap) {
        int nc = *cap ? *cap * 2 : 65536;
        while (nc < *len + n + 1) nc *= 2;
        char *nb = (char *)realloc(*buf, (size_t)nc);
        if (!nb) return;
        *buf = nb;
        *cap = nc;
    }
    memcpy(*buf + *len, s, (size_t)n);
    *len += n;
    (*buf)[*len] = 0;
}

static void appendVariantField(char **buf, int *len, int *cap, const Variant *v)
{
    if (!v) { appendUtf8(buf, len, cap, "?", 1); return; }
    if (v->vt == TVT_STRING && v->u.string) {
        VSString *vs = v->u.string;
        const wchar_t *dp = vs->LongString ? vs->LongString : vs->ShortString;
        int n = vs->Length;
        if (n < 0) n = 0;
        char *u8 = utf16ToUtf8(dp, n);
        if (u8) { appendUtf8(buf, len, cap, u8, (int)strlen(u8)); free(u8); }
    } else if (v->vt == TVT_INTEGER) {
        char tmp[32];
        _snprintf(tmp, sizeof(tmp), "%lld", (long long)v->u.integer);
        appendUtf8(buf, len, cap, tmp, (int)strlen(tmp));
    } else if (v->vt == TVT_REAL) {
        char tmp[64];
        _snprintf(tmp, sizeof(tmp), "%g", v->u.real);
        appendUtf8(buf, len, cap, tmp, (int)strlen(tmp));
    } else if (v->vt == TVT_VOID) {
        appendUtf8(buf, len, cap, "", 0);
    } else {
        appendUtf8(buf, len, cap, "?", 1);
    }
}

// runs on the main thread
static void doList(EvalOutcome *outcome)
{
    outcome->ok = 0;
    outcome->result = NULL;
    outcome->error = NULL;
    void *g = g_getScriptDispatch ? g_getScriptDispatch() : NULL;
    if (!g) { outcome->error = _strdup("TJS engine not ready"); return; }
    void **gvtbl = *(void ***)g;
    DispatchPropGetFn gPropGet = (DispatchPropGetFn)gvtbl[4];

    Variant oVar;
    memset(&oVar, 0, sizeof(oVar));
    unsigned long hint = 0;
    if (gPropGet(g, 0, L"o", &hint, &oVar, NULL) != 0 || oVar.vt != TVT_OBJECT || !oVar.u.closure.Object) {
        outcome->error = _strdup("global 'o' not found");
        return;
    }
    void *od = oVar.u.closure.Object;
    void **ovtbl = *(void ***)od;
    // 2016-era iTJSDispatch2 (no QueryInterface): [4]=PropGet, [11]=EnumMembers
    DispatchEnumMembersFn enumMembers = (DispatchEnumMembersFn)ovtbl[11];
    DispatchPropGetFn oPropGet = (DispatchPropGetFn)ovtbl[4];

    initMiniDispatch();
    KeyList kl;
    memset(&kl, 0, sizeof(kl));
    g_keySink = &kl;
    // callback closure: { Object = dispatch to call, ObjThis = NULL }
    void *closure[2] = { &miniDispatch, NULL };
    int erc = enumMembers(od, TJS_ENUM_NO_VALUE, closure, NULL);
    g_keySink = NULL;
    if (erc != 0) {
        char ebuf[128];
        _snprintf(ebuf, sizeof(ebuf), "enumMembers failed rc=%08X", (unsigned int)erc);
        outcome->error = _strdup(ebuf);
        for (int i = 0; i < kl.count; i++) free(kl.keys[i]);
        if (kl.keys) free(kl.keys);
        return;
    }

    if (kl.count <= 0) {
        outcome->result = _strdup("");
        outcome->ok = 1;
        for (int i = 0; i < kl.count; i++) free(kl.keys[i]);
        if (kl.keys) free(kl.keys);
        return;
    }

    char *buf = NULL;
    int blen = 0, bcap = 0;
    void *oObjThis = oVar.u.closure.ObjThis;
    for (int i = 0; i < kl.count; i++) {
        const wchar_t *key = kl.keys[i];
        Variant objVar;
        memset(&objVar, 0, sizeof(objVar));
        hint = 0;
        int rc1 = oPropGet(od, 0, key, &hint, &objVar, oObjThis);
        Variant nv, iv;
        memset(&nv, 0, sizeof(nv));
        memset(&iv, 0, sizeof(iv));
        if (rc1 == 0 && objVar.vt == TVT_OBJECT && objVar.u.closure.Object) {
            void *od2 = objVar.u.closure.Object;
            void **ovtbl2 = *(void ***)od2;
            DispatchPropGetFn p2 = (DispatchPropGetFn)ovtbl2[4];
            void *t2 = objVar.u.closure.ObjThis;
            hint = 0;
            p2(od2, 0, L"name", &hint, &nv, t2);
            hint = 0;
            p2(od2, 0, L"id", &hint, &iv, t2);
        }
        // key \t name \t id \n
        char *k8 = utf16ToUtf8(key, (int)wcslen(key));
        if (k8) { appendUtf8(&buf, &blen, &bcap, k8, (int)strlen(k8)); free(k8); }
        appendUtf8(&buf, &blen, &bcap, "\t", 1);
        appendVariantField(&buf, &blen, &bcap, &nv);
        appendUtf8(&buf, &blen, &bcap, "\t", 1);
        appendVariantField(&buf, &blen, &bcap, &iv);
        appendUtf8(&buf, &blen, &bcap, "\n", 1);
    }
    for (int i = 0; i < kl.count; i++) free(kl.keys[i]);
    if (kl.keys) free(kl.keys);

    outcome->result = buf ? buf : _strdup("");
    outcome->ok = 1;
}



// ---------------------------------------------------------------------------
// WndProc (main thread)
// ---------------------------------------------------------------------------
#define WM_TBC_EXEC (WM_USER + 0x46)

typedef struct _EvalRequest {
    char *code;    // utf8, NUL-terminated
    HANDLE done;   // completion event
    int ok;
    int scriptMode;
    int listMode;
    char *result;
    char *error;
} EvalRequest;

static LRESULT CALLBACK bridgeWndProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    (void)wp;
    if (msg == WM_TBC_EXEC) {
        EvalRequest *req = (EvalRequest *)lp;
        EvalOutcome oc;
        if (req->listMode) {
            doList(&oc);
        } else if (req->scriptMode) {
            doEvalScript(req->code, (int)strlen(req->code), &oc);
        } else {
            doEval(req->code, (int)strlen(req->code), &oc);
        }
        req->ok = oc.ok;
        req->result = oc.result;
        req->error = oc.error;
        char logbuf[4096];
        if (oc.ok) {
            int rl = oc.result ? (int)strlen(oc.result) : -1;
            _snprintf(logbuf, sizeof(logbuf), "EVAL OK [len=%d]: %.200s\n", rl, oc.result ? oc.result : "(null)");
        } else {
            _snprintf(logbuf, sizeof(logbuf), "EVAL ERR: %.200s\n", oc.error ? oc.error : "(null)");
        }
        logStr(logbuf);
        SetEvent(req->done);
        return 0;
    }
    return DefWindowProcW(hwnd, msg, wp, lp);
}

// ---------------------------------------------------------------------------
// pipe server thread
// ---------------------------------------------------------------------------
#define PIPE_NAME L"\\\\.\\pipe\\tbc_bridge"
#define MAX_CMD (512 * 1024)

static int writeAll(HANDLE h, const char *s, int len)
{
    int off = 0;
    while (off < len) {
        DWORD written = 0;
        if (!WriteFile(h, s + off, (DWORD)(len - off), &written, NULL) || written == 0)
            return 0;
        off += (int)written;
    }
    return 1;
}

static int readExact(HANDLE h, char *buf, int len)
{
    int got = 0;
    while (got < len) {
        DWORD r = 0;
        if (!ReadFile(h, buf + got, (DWORD)(len - got), &r, NULL) || r == 0)
            return 0;
        got += (int)r;
    }
    return 1;
}

static int writeErr(HANDLE h, const char *msg)
{
    int ml = (int)strlen(msg);
    char hdr[8];
    hdr[0] = 'E'; hdr[1] = 'R'; hdr[2] = 'R'; hdr[3] = '\n';
    hdr[4] = (char)(ml & 0xFF); hdr[5] = (char)((ml >> 8) & 0xFF);
    hdr[6] = (char)((ml >> 16) & 0xFF); hdr[7] = (char)((ml >> 24) & 0xFF);
    if (!writeAll(h, hdr, 8)) return 0;
    return writeAll(h, msg, ml);
}

static void handleClient(HANDLE hPipe)
{
    logStr("client connected\n");
    char cmd[16];
    int cmdLen = 0;
    char c;
    while (cmdLen < 16) {
        DWORD r = 0;
        if (!ReadFile(hPipe, &c, 1, &r, NULL) || r == 0) { logStr("cmd read failed\n"); return; }
        if (c == '\n') break;
        cmd[cmdLen++] = c;
    }
    logStr("cmd: ");
    { char tmp[32]; int k; for (k = 0; k < cmdLen && k < 20; k++) tmp[k] = cmd[k]; tmp[k] = 0; logStr(tmp); logStr("\n"); }
    if (cmdLen == 4 && memcmp(cmd, "PING", 4) == 0) {
        logStr("PING branch\n");
        int wr = writeAll(hPipe, "PONG\n", 5);
        logStr(wr ? "PONG written\n" : "PONG write FAILED\n");
        return;
    }
    if (cmdLen == 4 && memcmp(cmd, "LIST", 4) == 0) {
        logStr("LIST branch\n");
        HANDLE ev = CreateEventW(NULL, FALSE, FALSE, NULL);
        if (!ev) { writeErr(hPipe, "no event"); return; }
        if (!g_bridgeHwnd) { CloseHandle(ev); writeErr(hPipe, "no window"); return; }
        EvalRequest *req = (EvalRequest *)calloc(1, sizeof(EvalRequest));
        if (!req) { CloseHandle(ev); writeErr(hPipe, "no memory"); return; }
        req->done = ev;
        req->listMode = 1;
        PostMessageW(g_bridgeHwnd, WM_TBC_EXEC, 0, (LPARAM)req);
        DWORD wr = WaitForSingleObject(ev, 30000);
        if (wr == WAIT_OBJECT_0) {
            if (req->ok) {
                int rl = (int)strlen(req->result);
                writeAll(hPipe, "OK\n", 3);
                unsigned char l4[4] = { (unsigned char)(rl & 0xFF), (unsigned char)((rl >> 8) & 0xFF),
                                        (unsigned char)((rl >> 16) & 0xFF), (unsigned char)((rl >> 24) & 0xFF) };
                writeAll(hPipe, (char *)l4, 4);
                writeAll(hPipe, req->result, rl);
            } else {
                int el = (int)strlen(req->error);
                writeAll(hPipe, "ERR\n", 4);
                unsigned char l4[4] = { (unsigned char)(el & 0xFF), (unsigned char)((el >> 8) & 0xFF),
                                        (unsigned char)((el >> 16) & 0xFF), (unsigned char)((el >> 24) & 0xFF) };
                writeAll(hPipe, (char *)l4, 4);
                writeAll(hPipe, req->error, el);
            }
        } else {
            writeErr(hPipe, "timeout");
        }
        if (req->result) free(req->result);
        if (req->error) free(req->error);
        free(req);
        CloseHandle(ev);
        return;
    }
    if (cmdLen != 4 || memcmp(cmd, "EVAL", 4) != 0) {
        // EVALS = script-mode eval
        if (cmdLen == 5 && memcmp(cmd, "EVALS", 5) == 0) {
            unsigned char lenBytes[4];
            if (!readExact(hPipe, (char *)lenBytes, 4)) return;
            unsigned int codeLen = lenBytes[0] | (lenBytes[1] << 8) | (lenBytes[2] << 16) | ((unsigned int)lenBytes[3] << 24);
            if (codeLen > MAX_CMD) { writeErr(hPipe, "code too long"); return; }
            char *code = (char *)malloc(codeLen + 1);
            if (!code) { writeErr(hPipe, "no memory"); return; }
            if (!readExact(hPipe, code, (int)codeLen)) { free(code); return; }
            code[codeLen] = 0;
            HANDLE ev = CreateEventW(NULL, FALSE, FALSE, NULL);
            if (!ev) { free(code); writeErr(hPipe, "no event"); return; }
            if (!g_bridgeHwnd) { CloseHandle(ev); free(code); writeErr(hPipe, "no window"); return; }
            EvalRequest *req = (EvalRequest *)calloc(1, sizeof(EvalRequest));
            if (!req) { CloseHandle(ev); free(code); writeErr(hPipe, "no memory"); return; }
            req->code = code;
            req->done = ev;
            req->scriptMode = 1;
            PostMessageW(g_bridgeHwnd, WM_TBC_EXEC, 0, (LPARAM)req);
            DWORD wr = WaitForSingleObject(ev, 30000);
            if (wr == WAIT_OBJECT_0) {
                if (req->ok) {
                    int rl = (int)strlen(req->result);
                    writeAll(hPipe, "OK\n", 3);
                    unsigned char l4[4] = { (unsigned char)(rl & 0xFF), (unsigned char)((rl >> 8) & 0xFF),
                                            (unsigned char)((rl >> 16) & 0xFF), (unsigned char)((rl >> 24) & 0xFF) };
                    writeAll(hPipe, (char *)l4, 4);
                    writeAll(hPipe, req->result, rl);
                } else {
                    int el = (int)strlen(req->error);
                    writeAll(hPipe, "ERR\n", 4);
                    unsigned char l4[4] = { (unsigned char)(el & 0xFF), (unsigned char)((el >> 8) & 0xFF),
                                            (unsigned char)((el >> 16) & 0xFF), (unsigned char)((el >> 24) & 0xFF) };
                    writeAll(hPipe, (char *)l4, 4);
                    writeAll(hPipe, req->error, el);
                }
            } else {
                writeErr(hPipe, "timeout");
            }
            if (req->result) free(req->result);
            if (req->error) free(req->error);
            if (req->code) free(req->code);
            free(req);
            CloseHandle(ev);
            return;
        }
        logStr("bad command\n");
        writeErr(hPipe, "bad command");
        return;
    }
    unsigned char lenBytes[4];
    if (!readExact(hPipe, (char *)lenBytes, 4)) { logStr("len read failed\n"); return; }
    unsigned int codeLen = lenBytes[0] | (lenBytes[1] << 8) | (lenBytes[2] << 16) | ((unsigned int)lenBytes[3] << 24);
    logStr("codeLen: ");
    { char tmp[32]; _snprintf(tmp, sizeof(tmp), "%u\n", codeLen); logStr(tmp); }
    if (codeLen > MAX_CMD) {
        writeErr(hPipe, "code too long");
        return;
    }
    char *code = (char *)malloc(codeLen + 1);
    if (!code) { writeErr(hPipe, "no memory"); return; }
    if (!readExact(hPipe, code, (int)codeLen)) { free(code); logStr("code read failed\n"); return; }
    code[codeLen] = 0;
    logStr("code received\n");

    HANDLE ev = CreateEventW(NULL, FALSE, FALSE, NULL);
    if (!ev) { free(code); writeErr(hPipe, "no event"); return; }
    if (!g_bridgeHwnd) { CloseHandle(ev); free(code); writeErr(hPipe, "no window"); return; }

    EvalRequest *req = (EvalRequest *)calloc(1, sizeof(EvalRequest));
    if (!req) { CloseHandle(ev); free(code); writeErr(hPipe, "no memory"); return; }
    req->code = code;
    req->done = ev;

    PostMessageW(g_bridgeHwnd, WM_TBC_EXEC, 0, (LPARAM)req);
    logStr("posted WM_TBC_EXEC, waiting\n");
    DWORD wr = WaitForSingleObject(ev, 30000);
    logStr(wr == WAIT_OBJECT_0 ? "wndproc done\n" : "WAIT TIMEOUT, waiting more\n");
    if (wr != WAIT_OBJECT_0) {
        // wait again: the main thread may be busy; never free the request
        // while a WM_TBC_EXEC message could still be pending.
        wr = WaitForSingleObject(ev, 20000);
        logStr(wr == WAIT_OBJECT_0 ? "wndproc done (late)\n" : "STILL TIMEOUT, leaking request\n");
    }
    if (wr == WAIT_OBJECT_0) {
        if (req->ok) {
            int rl = (int)strlen(req->result);
            int w1 = writeAll(hPipe, "OK\n", 3);
            unsigned char l4[4] = { (unsigned char)(rl & 0xFF), (unsigned char)((rl >> 8) & 0xFF),
                                    (unsigned char)((rl >> 16) & 0xFF), (unsigned char)((rl >> 24) & 0xFF) };
            int w2 = writeAll(hPipe, (char *)l4, 4);
            int w3 = writeAll(hPipe, req->result, rl);
            { char tmp[64]; _snprintf(tmp, sizeof(tmp), "resp OK len=%d w=%d,%d,%d\n", rl, w1, w2, w3); logStr(tmp); }
        } else {
            int el = (int)strlen(req->error);
            int w1 = writeAll(hPipe, "ERR\n", 4);
            unsigned char l4[4] = { (unsigned char)(el & 0xFF), (unsigned char)((el >> 8) & 0xFF),
                                    (unsigned char)((el >> 16) & 0xFF), (unsigned char)((el >> 24) & 0xFF) };
            int w2 = writeAll(hPipe, (char *)l4, 4);
            int w3 = writeAll(hPipe, req->error, el);
            { char tmp[64]; _snprintf(tmp, sizeof(tmp), "resp ERR len=%d w=%d,%d,%d\n", el, w1, w2, w3); logStr(tmp); }
        }
    } else {
        writeErr(hPipe, "timeout");
        logStr("resp timeout\n");
    }
    if (req->result) free(req->result);
    if (req->error) free(req->error);
    if (req->code) free(req->code);
    free(req);
    CloseHandle(ev);
}

static DWORD WINAPI pipeThread(LPVOID arg)
{
    (void)arg;
    while (1) {
        HANDLE hPipe = CreateNamedPipeW(PIPE_NAME, PIPE_ACCESS_DUPLEX,
            PIPE_TYPE_BYTE | PIPE_READMODE_BYTE | PIPE_WAIT, 1,
            1024 * 1024, 1024 * 1024, 0, NULL);
        if (hPipe == INVALID_HANDLE_VALUE) {
            Sleep(100);
            continue;
        }
        BOOL ok = ConnectNamedPipe(hPipe, NULL);
        if (!ok && GetLastError() != ERROR_PIPE_CONNECTED) {
            CloseHandle(hPipe);
            continue;
        }
        handleClient(hPipe);
        FlushFileBuffers(hPipe); // ensure response bytes reach the client before disconnect
        DisconnectNamedPipe(hPipe);
        CloseHandle(hPipe);
    }
    return 0;
}

// ---------------------------------------------------------------------------
// V2Link / V2Unlink (exported undecorated thanks to --kill-at)
// ---------------------------------------------------------------------------
static iTVPFunctionExporter *g_exporter = NULL;

HRESULT __stdcall V2Link(iTVPFunctionExporter *exporter)
{
    g_exporter = exporter;
    // resolve exporter vtable method: object memory = [vptr][...]; vptr points
    // to the real function table [QueryFunctions, QueryFunctionsByNarrowString, ...]
    void **vtbl = *(void ***)exporter;
    QueryNarrowFn qn = (QueryNarrowFn)vtbl[1];
    const char *names[6] = {
        "iTJSDispatch2 * ::TVPGetScriptDispatch()",
        "void ::TVPExecuteExpression(const ttstr &,tTJSVariant *)",
        "tTJSVariantString * ::TJSAllocVariantString(const tjs_char *)",
        "void ::TVPDoTryBlock(tTVPTryBlockFunction,tTVPCatchBlockFunction,tTVPFinallyBlockFunction,void *)",
        "void ::TVPExecuteScript(const ttstr &,const ttstr &,tjs_int,tTJSVariant *)",
        "void ::TVPExecuteStorage(const ttstr &,tTJSVariant *,bool,const tjs_char *)",
    };
    void *funcs[6] = { NULL, NULL, NULL, NULL, NULL, NULL };
    qn(exporter, names, funcs, 6);
    g_getScriptDispatch = (GetScriptDispatchFn)funcs[0];
    g_executeExpression = (ExecuteExpressionFn)funcs[1];
    g_allocVariantString = (AllocVariantStringFn)funcs[2];
    g_doTryBlock = (DoTryBlockFn)funcs[3];
    g_executeScript = (ExecuteScriptFn)funcs[4];
    g_executeStorage = (ExecuteStorageFn)funcs[5];

    // determine game dir (parent of the exe)
    wchar_t path[1024];
    DWORD n = GetModuleFileNameW(NULL, path, 1024);
    if (n > 0 && n < 1024) {
        // strip file name -> exe dir
        while (n > 0 && path[n - 1] != '\\') n--;
        while (n > 0 && path[n - 1] == '\\') n--;
        if (n > 0) {
            memcpy(g_logDir, path, n * 2);
            g_logDir[n] = 0;
        }
    }

    logStr("=== tbc_bridge V2Link ===\n");
    char buf[512];
    _snprintf(buf, sizeof(buf),
        "exporter=%p\nTVPGetScriptDispatch=%p TVPExecuteScript=%p TJSAllocVariantString=%p TVPDoTryBlock=%p\n",
        exporter, funcs[0], funcs[1], funcs[2], funcs[3]);
    logStr(buf);

    // hidden window on the main thread
    WNDCLASSW wc;
    memset(&wc, 0, sizeof(wc));
    wc.lpfnWndProc = bridgeWndProc;
    wc.lpszClassName = L"tbc_bridge_wnd";
    if (RegisterClassW(&wc)) {
        g_bridgeHwnd = CreateWindowExW(0, L"tbc_bridge_wnd", L"tbc", 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL);
        if (!g_bridgeHwnd) logStr("CreateWindowExW failed\n");
    } else {
        logStr("RegisterClassW failed\n");
    }

    HANDLE th = CreateThread(NULL, 0, pipeThread, NULL, 0, NULL);
    if (th) CloseHandle(th);
    return S_OK;
}

HRESULT __stdcall V2Unlink(void)
{
    if (g_bridgeHwnd) DestroyWindow(g_bridgeHwnd);
    logStr("=== tbc_bridge V2Unlink ===\n");
    return S_OK;
}





